name: UhcCore
main: com.gmail.val59000mc.UhcCore
version: @version@
description: Automates UHC games on a dedicated server (Modded)
authors: [ val59000mc, Mezy, Milkory, LoliColleen ]
softdepend: [ WorldEdit, Vault, ProtocolLib, MMOItems, RabbiFourneau ]
api-version: 1.13
commands:
  uhccore:
    description: "Type '/uhccore help' to see a list of commands"
    usage: "/uhccore <sub-command> (Debug command only!)"
  chat:
    description: "Type '/chat' to toggle global chat"
    usage: "/chat"
    aliases: [ c ]
  teleport:
    description: "Type '/teleport <player>' to teleport to your teammates while spectating"
    usage: "/teleport <player>"
    aliases: [ tp ]
  start:
    description: "This command is used to toggle force starting of the game"
    usage: /<command>
    permission: "uhc-core.commands.start"
  scenarios:
    description: "This command is used to view and toggle scenarios."
    usage: /<command>
    aliases: [ game, settings, uhc ]
  teaminventory:
    description: "This command is used to open team inventory."
    usage: /<command>
    aliases: [ ti, backpack, bp ]
  hub:
    description: "This command is used to return back to the hub."
    usage: /<command>
    aliases: [ lobby, leave, spawn ]
  iteminfo:
    description: "This command is used to get the right item data for the config."
    usage: "/<command> while holding a item."
    permission: "uhc-core.commands.iteminfo"
  revive:
    description: "You can use this command to let a death player respawn in the game."
    usage: /<command> <player>
    permission: "uhc-core.commands.revive"
  seed:
    description: "This command is overridden from the vanilla /seed command to stop confusion."
    usage: /<command>
    permission: "minecraft.command.seed"
  crafts:
    description: "This command is used to open the custom crafting recipes menu"
    usage: /<command>
    aliases: [ craft, recipe, recipes ]
  top:
    description: "This command teleports players to the highest block above their head"
    usage: /<command>
    permission: "uhc-core.commands.top"
  spectate:
    description: "This command can be used to set yourself as spectator at the start of the game."
    usage: /<command>
    permission: "uhc-core.commands.spectate"
  upload:
    description: "This command can be used to upload a certain file to hastebin.com."
    usage: /<command> <file-type>
    permission: "uhc-core.commands.upload"
  deathmatch:
    description: "This command can be used to force-start the deathmatch."
    usage: /<command> start
    permission: "uhc-core.commands.deathmatch"
  team:
    description: "Used to manage teams."
    usage: /<command> <sub-command>
  setscenario:
    description: "Used to set scenario."
    usage: /<command> <string>
    permission: "uhc-core.commands.setscenario"
    aliases: [ setscenario, enablescenario ]
permissions:
  uhc-core.defaults:
    description: "Permission of default."
    default: true
  uhc-core.craft.quick-pick:
    description: "Permission of craft."
    default: true
  uhc-core.craft.king's-rod:
    description: "Permission of craft."
    default: true
  uhc-core.craft.forge:
    description: "Permission of craft."
    default: true
  uhc-core.craft.copper-shield:
    description: "Permission of craft."
    default: true
  uhc-core.craft.apprentice-sword:
    description: "Permission of craft."
    default: true
  uhc-core.craft.dragon-sword:
    description: "Permission of craft."
    default: true
  uhc-core.craft.apprentice-bow:
    description: "Permission of craft."
    default: true
  uhc-core.craft.cupid's-bow:
    description: "Permission of craft."
    default: true
  uhc-core.craft.apprentice-helmet:
    description: "Permission of craft."
    default: true
  uhc-core.craft.spiked-armor:
    description: "Permission of craft."
    default: true
  uhc-core.craft.dragon-armor:
    description: "Permission of craft."
    default: true
  uhc-core.craft.seven-league-boots:
    description: "Permission of craft."
    default: true
  uhc-core.craft.golden-head:
    description: "Permission of craft."
    default: true